id: ICC74E741
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:33:44+00:00'
last_modified: '2022-06-08T08:53:36.130737+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23951
  title: ཕ་འབྲུག་སྒོམ་ཞིག་པོའི་རྣམ་པར་ཐར་པ་ཐུགས་རྗེའི་ཆུ་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F64:
      image_group_id: I3549
      title: ''
      total_pages: 120
      order: 1
      base_file: 4F64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
