id: P009138
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:50.846832
source_metadata:
  id: bdr:W23951
  title: ཕ་འབྲུག་སྒོམ་ཞིག་པོའི་རྣམ་པར་ཐར་པ་ཐུགས་རྗེའི་ཆུ་རྒྱུན
  author: ''
  volumes:
    26264a64dcd046b5bb508c698b96a430:
      image_group_id: I3549
      title: ''
      volume_number: 1
      total_pages: 120
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
